# Generated by Django 6.1 on 2026-09-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('estado', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
