# Generated by Django 6.1 on 2026-09-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudesApp', '0002_datos_iniciales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
