# Generated by Django 6.1 on 2026-09-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('requisitos', models.JSONField(default=list)),
                ('dias_habiles', models.PositiveSmallIntegerField()),
                ('costo', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
    ]
