# Generated by Django 6.1 on 2026-09-28 01:22

import django.db.models.deletion
from django.db import migrations, models


def copiar_requisitos(apps, schema_editor):
    Servicio = apps.get_model('serviciosApp', 'Servicio')
    Requisito = apps.get_model('serviciosApp', 'Requisito')

    requisitos = []
    for servicio in Servicio.objects.using(schema_editor.connection.alias).all():
        for descripcion in servicio.requisitos or []:
            requisitos.append(Requisito(servicio_id=servicio.pk, descripcion=descripcion))

    Requisito.objects.using(schema_editor.connection.alias).bulk_create(requisitos)


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosApp', '0002_corregir_nombre_permiso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_migracion', to='serviciosApp.servicio')),
            ],
        ),
        migrations.RunPython(copiar_requisitos, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='servicio',
            name='requisitos',
        ),
        migrations.AlterField(
            model_name='requisito',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='serviciosApp.servicio'),
        ),
    ]
