# Generated by Django 6.1 on 2026-09-28 01:33

import django.db.models.deletion
import unicodedata
from django.db import migrations, models


def convertir_categorias(apps, schema_editor):
    Categoria = apps.get_model('serviciosApp', 'Categoria')
    Servicio = apps.get_model('serviciosApp', 'Servicio')
    alias = schema_editor.connection.alias

    def clave(nombre):
        return ''.join(
            caracter
            for caracter in unicodedata.normalize('NFKD', nombre.casefold())
            if not unicodedata.combining(caracter)
        )

    categorias = {
        clave(categoria.nombre): categoria
        for categoria in Categoria.objects.using(alias).all()
    }
    for nombre in Servicio.objects.using(alias).values_list('categoria', flat=True).distinct():
        categorias.setdefault(
            clave(nombre),
            Categoria.objects.using(alias).create(nombre=nombre),
        )
    for servicio in Servicio.objects.using(alias).all():
        servicio.categoria_nueva_id = categorias[clave(servicio.categoria)].pk
        servicio.save(update_fields=['categoria_nueva'])


class Migration(migrations.Migration):

    dependencies = [
        ('serviciosApp', '0003_remove_servicio_requisitos_requisito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='servicio',
            name='categoria_nueva',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_nuevos', to='serviciosApp.categoria'),
        ),
        migrations.RunPython(convertir_categorias, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='servicio',
            name='categoria',
        ),
        migrations.RenameField(
            model_name='servicio',
            old_name='categoria_nueva',
            new_name='categoria',
        ),
        migrations.AlterField(
            model_name='servicio',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='serviciosApp.categoria'),
        ),
    ]
